language: python
python:
- 2.7
branches:
  only:
  - master
install:
- pip install -r requirements.txt
script:
- make -C pelican publish github
env:
  global:
    secure: jSQBezsKgS6AYWW6EM/NXuSOxGDH0sYVf5skp7/s8D45fRvdcGa8FwTG2wOsA8VGHvPqxzNyICSeDuMEZKPhbynv2dBBDxWCfAw9R26zed3Blx9+frE5iOnAxrLYwtoskJcaGW29DiaVvg1cLi1JbYwPBFOlUWPFgXiBWf27ngspvZCa6H0c4ftMKAXfyHTDutRKGNk8MXvUHKts52OpW2TBE3PXVNOhkLg6ZXAzN7SXTKEfTwT1oFF2eaXWL+vkgUTXprGUjh9Ewn2BhcHwrBYB/0tph0P5l7czYO0u/+wevUh/qmqciCE4Jbzl2UX3035rElu2uw7DRc97YkBvjuHMHHDQlsuvj9XtP7Ymzvf6By0GbXfmYku3pvCMEfMO8lh/S8FgAoMV+9RJFzaKdKQLjyKi3StG0s4xQ4Y4crQqx/a13RFVSVNMIkKCVQrHtEjURGY0Hue+5N3ISE67acKsWFCbeEFajtAZvL2xlhB5g69pD8y8TLUPxQvxLYDKEBUd0SkSfw7nhZrAS5kW8/FQqAeLzzLteiXENBQHP2bTEhvv9GcIYSC8zFlfbL2upkDjJON39BgKLn9e6AFTzwzaEFMhS81N1tScGjpQE2T2aupxwefgFPwJ6zjSlYaTHkpPM+XYSu0713acqbkfScIT/M8gAaM15QKJpKG/xJQ=
